### PR TITLE
docs(roadmap): Update ROADMAP.md

### PR DESCRIPTION
**Pull request by jakeschurch**
- ROADMAP.md is stale and was last updated in August 2018 - needed to be
updated for new/revised round of development

### CODE REVIEW

**Comment by jakeschurch** [comment]
@Plotnus do you mind just quickly looking this over and making sure this seems both reasonable and in-scope?

**Comment by Plotnus** [comment]
@jakeschurch

I think this is good for now.
I think it will change as we learn more.

I think we should add looking at some commercial packages and example systems to help inform us of things we need and how to split things up.

Eg., from [QuantHouse](https://www.quanthouse.com/AlgoTradingSolutions.html) we see `MarketDataAdapters` and `ExecutionAdapters` which gives us words for what we were going for with `Broker` and `Data`. It also makes me think we sholud keep portfolio separate assuming that the Executor of our trades sends us Events saying about submitted order status.

I guess all this points to "add references", and "collect references". Just a few good ones that can inform our first pass & help break things up nicely. 

Your thoughts?

**Comment by jakeschurch** [comment]
@Plotnus thanks for getting back


> 
> I think this is good for now.
> I think it will change as we learn more.

Great. I will merge this PR and close issue #4 
>
> I think we should add looking at some commercial packages and example systems to help inform us of things we need and how to split things up.

This was the next thing I planned on looking into - using our notes in discord as well as from some of the example systems - I'm planning on drafting a technical release log for v1.0 _(under Releases)_ in order have a _fairly-filled_ outline of the agreed-upon semantics and their related functionality.
> 
> Eg., from [QuantHouse](https://www.quanthouse.com/AlgoTradingSolutions.html) we see `MarketDataAdapters` and `ExecutionAdapters` which gives us words for what we were going for with `Broker` and `Data`. 

Absolutely
> It also makes me think we sholud keep portfolio separate assuming that the Executor of our trades sends us Events saying about submitted order status.

- Everything that can be modeled by a type/trait/struct that isn't already most likely will be.
- I see pub/sub model/callbacks coming into play later down the line.
> 
> I guess all this points to "add references", and "collect references". Just a few good ones that can inform our first pass & help break things up nicely.

- As long as the outcome doesn't turn into a custom db/dbms that's fine with me :wink: 
- And yeah - again pointing to idea about v1.0 releases.
> 
> Your thoughts?

**Comment by jakeschurch** [comment]
@Plotnus I created the v1.0 Release Draft document in the trade_rs google docs dir if you want to help out with that whenev :+1:

**Pull request merged**
